### ISSUE TITLE
User can manage (view/edit/delete) past availability requests

### ISSUE THREAD

**Issue by joshrieken** [tiwatson/wanderinglabs-availability#3]
There is no authentication at present, so we need some relatively secure way to allow only users who own the request to edit it.

Ideas:

1.) Send tokened link via email

**Comment by tiwatson** [comment]
There is actually code in place that populates a table of AvailabiltyRequests. 

Just turned off at the moment. See:

https://github.com/tiwatson/wanderinglabs-availability/blob/master/app/assets/templates/availability_requests/index.html.haml

https://github.com/tiwatson/wanderinglabs-availability/blob/master/app/assets/javascripts/availability_requests/service.js

**Comment by joshrieken** [comment]
Right on. Mind if I take this one?

**Comment by tiwatson** [comment]
Go for it. 

Users should have a usable auth token in place on their record. 
https://github.com/tiwatson/wanderinglabs-availability/blob/master/app/models/user.rb

**Comment by joshrieken** [comment]
It took me awhile to swing back around on this, but here's what I've come up with:
1. When not signed up / in:
   1. User must sign in / up before an availability request can be created.
   2. Instead of having a Submit button and an Email Address field, there will be copy and buttons/links for Sign Up and Sign In. Each link will launch a modal (thinking I'll try to use Refills for this).
   3. Sign In modal will have a Forgot Password link for those who need to set / reset their password.
2. When signed up / in:
   1. The Submit button will be present in the Create form, and the user is allowed to create.
   2. A list/table of availability requests will appear below the create form.
      1. Each request will have an Edit link, which will bring user to an edit form (thinking modal, using the same form as create).
      2. Each will also have a Delete link.

I just finished authentication similar to this for an Angular + Rails app, so I'm willing and able to do it.

We may need a special flow for current users. Maybe we can send them an email with a link to set their password for the first time instead of requiring them to go through the Forgot Password process.

A simpler alternative is to use just Rails views for sign in / up and forgot password, but I've done this with Angular before and know how, and it's a smoother user experience, so I figure, why not?

Thoughts?

**Comment by tiwatson** [comment]
Just because this is a single model crud app, no preferences, no payment.. and just a little side project, I'd like to take it away from the norm and try to go without the standard log in/sign up process. 

I'd like to think it doesn't need any authentication at all. I don't anyone would ever mess with each others accounts, but realistically I guess it does need something. 

I've had a few more questions from users about managing their requests and a few other other items and now that I finished up the infographic project I'm going to jump back on some update on this project for a week or two. Keeping it quick, simple and dirty. I'll probably take a crack at the token auth in the next day or two unless you want dibs on it.

**Comment by joshrieken** [comment]
Sounds good. I haven't done any coding or anything on it. All yours!
